name: Build on push
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with: 
          cache: true
      - run: flutter pub get
      - run: flutter build web
      - run: ls ${{ github.workspace }}
      - run: ls
      - run: cd build
      - run: ls
      - run: cd docs
      - run: ls
      
      
      
      
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "build/web/"
#           target: "docs/"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/favicon.png"
#           target: "/docs/favicon.png"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/.last_build_id"
#           target: "/docs/.last_build_id"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/flutter_service_worker.js"
#           target: "/docs/flutter_service_worker.js"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/index.html"
#           target: "/docs/index.html"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/main.dart.js"
#           target: "/docs/main.dart.js"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/manifest.json"
#           target: "/docs/manifest.json"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/version.json"
#           target: "/docs/version.json"
      
#       - uses: canastro/copy-file-action@master
#         with:
#           source: "/build/web/icons"
#           target: "/docs/icons"
      
